export const OecdcountryList = () => {
  return (
    <>
      <option value='United States'>United States</option>
      <option value='United Kingdom'>United Kingdom</option>
      <optgroup>
        <option className='text-uppercase'>Europe & United Kingdom</option>
        <option value='Aland Islands'>Åland Islands</option>
        <option value='Albania'>Albania</option>
        <option value='Andorra'>Andorra</option>
        <option value='Austria'>Austria</option>
        <option value='Belarus'>Belarus</option>
        <option value='Belgium'>Belgium</option>
        <option value='Bosnia and Herzegovina'>Bosnia & Herzegovina</option>
        <option value='Bulgaria'>Bulgaria</option>
        <option value='Croatia'>Croatia</option>
        <option value='Czech Republic'>Czechia</option>
        <option value='Denmark'>Denmark</option>
        <option value='Estonia'>Estonia</option>
        <option value='Faroe Islands'>Faroe Islands</option>
        <option value='Finland'>Finland</option>
        <option value='France'>France</option>
        <option value='Germany'>Germany</option>
        <option value='Gibraltar'>Gibraltar</option>
        <option value='Greece'>Greece</option>
        <option value='Guernsey'>Guernsey</option>
        <option value='Holy See (Vatican City State)'>Vatican City</option>
        <option value='Hungary'>Hungary</option>
        <option value='Iceland'>Iceland</option>
        <option value='Ireland'>Ireland</option>
        <option value='Isle of Man'>Isle of Man</option>
        <option value='Italy'>Italy</option>
        <option value='Jersey'>Jersey</option>
        <option value='Kosovo'>Kosovo</option>
        <option value='Latvia'>Latvia</option>
        <option value='Liechtenstein'>Liechtenstein</option>
        <option value='Lithuania'>Lithuania</option>
        <option value='Luxembourg'>Luxembourg</option>
        <option value='Macedonia, the Former Yugoslav Republic of'>North Macedonia</option>
        <option value='Malta'>Malta</option>
        <option value='Moldova, Republic of'>Moldova</option>
        <option value='Monaco'>Monaco</option>
        <option value='Montenegro'>Montenegro</option>
        <option value='Netherlands'>Netherlands</option>
        <option value='Norway'>Norway</option>
        <option value='Poland'>Poland</option>
        <option value='Portugal'>Portugal</option>
        <option value='Romania'>Romania</option>
        <option value='San Marino'>San Marino</option>
        <option value='Serbia'>Serbia</option>
        <option value='Serbia and Montenegro'>Serbia</option>
        <option value='Slovakia'>Slovakia</option>
        <option value='Slovenia'>Slovenia</option>
        <option value='Spain'>Spain</option>
        <option value='Svalbard and Jan Mayen'>Svalbard & Jan Mayen</option>
        <option value='Sweden'>Sweden</option>
        <option value='Switzerland'>Switzerland</option>
        <option value='Ukraine'>Ukraine</option>
        <option value='United Kingdom'>United Kingdom</option>
      </optgroup>
      <optgroup>
        <option className='text-uppercase'>Australia</option>
        <option value='American Samoa'>American Samoa</option>
        <option value='Australia'>Australia</option>
        <option value='Cook Islands'>Cook Islands</option>
        <option value='Fiji'>Fiji</option>
        <option value='French Polynesia'>French Polynesia</option>
        <option value='Guam'>Guam</option>
        <option value='Kiribati'>Kiribati</option>
        <option value='Marshall Islands'>Marshall Islands</option>
        <option value='Micronesia, Federated States of'>Micronesia</option>
        <option value='Nauru'>Nauru</option>
        <option value='New Caledonia'>New Caledonia</option>
        <option value='New Zealand'>New Zealand</option>
        <option value='Niue'>Niue</option>
        <option value='Norfolk Island'>Norfolk Island</option>
        <option value='Northern Mariana Islands'>Northern Mariana Islands</option>
        <option value='Palau'>Palau</option>
        <option value='Papua New Guinea'>Papua New Guinea</option>
        <option value='Pitcairn'>Pitcairn Islands</option>
        <option value='Samoa'>Samoa</option>
        <option value='Solomon Islands'>Solomon Islands</option>
        <option value='Tokelau'>Tokelau</option>
        <option value='Tonga'>Tonga</option>
        <option value='Tuvalu'>Tuvalu</option>
        <option value='Vanuatu'>Vanuatu</option>
        <option value='Wallis and Futuna'>Wallis & Futuna</option>
      </optgroup>
      <optgroup>
        <option className='text-uppercase'>North America</option>
        <option value='Anguilla'>Anguilla</option>
        <option value='Antigua and Barbuda'>Antigua & Barbuda</option>
        <option value='Aruba'>Aruba</option>
        <option value='Bahamas'>Bahamas</option>
        <option value='Barbados'>Barbados</option>
        <option value='Belize'>Belize</option>
        <option value='Bermuda'>Bermuda</option>
        <option value='Bonaire, Sint Eustatius and Saba'>Caribbean Netherlands</option>
        <option value='Canada'>Canada</option>
        <option value='Cayman Islands'>Cayman Islands</option>
        <option value='Costa Rica'>Costa Rica</option>
        <option value='Cuba'>Cuba</option>
        <option value='Curacao'>Curaçao</option>
        <option value='Dominica'>Dominica</option>
        <option value='Dominican Republic'>Dominican Republic</option>
        <option value='El Salvador'>El Salvador</option>
        <option value='Greenland'>Greenland</option>
        <option value='Grenada'>Grenada</option>
        <option value='Guadeloupe'>Guadeloupe</option>
        <option value='Guatemala'>Guatemala</option>
        <option value='Haiti'>Haiti</option>
        <option value='Honduras'>Honduras</option>
        <option value='Jamaica'>Jamaica</option>
        <option value='Martinique'>Martinique</option>
        <option value='Mexico'>Mexico</option>
        <option value='Montserrat'>Montserrat</option>
        <option value='Netherlands Antilles'>Curaçao</option>
        <option value='Nicaragua'>Nicaragua</option>
        <option value='Panama'>Panama</option>
        <option value='Puerto Rico'>Puerto Rico</option>
        <option value='Saint Barthelemy'>St. Barthélemy</option>
        <option value='Saint Kitts and Nevis'>St. Kitts & Nevis</option>
        <option value='Saint Lucia'>St. Lucia</option>
        <option value='Saint Martin'>St. Martin</option>
        <option value='Saint Pierre and Miquelon'>St. Pierre & Miquelon</option>
        <option value='Saint Vincent and the Grenadines'>St. Vincent & Grenadines</option>
        <option value='Sint Maarten'>Sint Maarten</option>
        <option value='Trinidad and Tobago'>Trinidad & Tobago</option>
        <option value='Turks and Caicos Islands'>Turks & Caicos Islands</option>
        <option value='United States'>United States</option>
        <option value='United States Minor Outlying Islands'>U.S. Outlying Islands</option>
        <option value='Virgin Islands, British'>British Virgin Islands</option>
        <option value='Virgin Islands, U.s.'>U.S. Virgin Islands</option>
        <optgroup></optgroup>
        <option className='text-uppercase'>South America</option>
        <option value='Argentina'>Argentina</option>
        <option value='Bolivia'>Bolivia</option>
        <option value='Brazil'>Brazil</option>
        <option value='Chile'>Chile</option>
        <option value='Colombia'>Colombia</option>
        <option value='Ecuador'>Ecuador</option>
        <option value='Falkland Islands (Malvinas)'>Falkland Islands (Islas Malvinas)</option>
        <option value='French Guiana'>French Guiana</option>
        <option value='Guyana'>Guyana</option>
        <option value='Paraguay'>Paraguay</option>
        <option value='Peru'>Peru</option>
        <option value='Suriname'>Suriname</option>
        <option value='Uruguay'>Uruguay</option>
        <option value='Venezuela'>Venezuela</option>
        <option value='American Samoa'>American Samoa</option>
        <option value='Australia'>Australia</option>
        <option value='Cook Islands'>Cook Islands</option>
        <option value='Fiji'>Fiji</option>
        <option value='French Polynesia'>French Polynesia</option>
        <option value='Guam'>Guam</option>
        <option value='Kiribati'>Kiribati</option>
        <option value='Marshall Islands'>Marshall Islands</option>
        <option value='Micronesia, Federated States of'>Micronesia</option>
        <option value='Nauru'>Nauru</option>
        <option value='New Caledonia'>New Caledonia</option>
        <option value='New Zealand'>New Zealand</option>
        <option value='Niue'>Niue</option>
        <option value='Norfolk Island'>Norfolk Island</option>
        <option value='Northern Mariana Islands'>Northern Mariana Islands</option>
        <option value='Palau'>Palau</option>
        <option value='Papua New Guinea'>Papua New Guinea</option>
        <option value='Pitcairn'>Pitcairn Islands</option>
        <option value='Samoa'>Samoa</option>
        <option value='Solomon Islands'>Solomon Islands</option>
        <option value='Tokelau'>Tokelau</option>
        <option value='Tonga'>Tonga</option>
        <option value='Tuvalu'>Tuvalu</option>
        <option value='Vanuatu'>Vanuatu</option>
        <option value='Wallis and Futuna'>Wallis & Futuna</option>
      </optgroup>
      <optgroup>
        <option className='text-uppercase'>Asia</option>
        <option value='Afghanistan'>Afghanistan</option>
        <option value='Armenia'>Armenia</option>
        <option value='Azerbaijan'>Azerbaijan</option>
        <option value='Bahrain'>Bahrain</option>
        <option value='Bangladesh'>Bangladesh</option>
        <option value='Bhutan'>Bhutan</option>
        <option value='British Indian Ocean Territory'>British Indian Ocean Territory</option>
        <option value='Brunei Darussalam'>Brunei</option>
        <option value='Cambodia'>Cambodia</option>
        <option value='China'>China</option>
        <option value='Christmas Island'>Christmas Island</option>
        <option value='Cocos (Keeling) Islands'>Cocos (Keeling) Islands</option>
        <option value='Cyprus'>Cyprus</option>
        <option value='Georgia'>Georgia</option>
        <option value='Hong Kong'>Hong Kong</option>
        <option value='India'>India</option>
        <option value='Indonesia'>Indonesia</option>
        <option value='Iran, Islamic Republic of'>Iran</option>
        <option value='Iraq'>Iraq</option>
        <option value='Israel'>Israel</option>
        <option value='Japan'>Japan</option>
        <option value='Jordan'>Jordan</option>
        <option value='Kazakhstan'>Kazakhstan</option>
        <option value="Korea, Democratic People's Republic of">North Korea</option>
        <option value='Korea, Republic of'>South Korea</option>
        <option value='Kuwait'>Kuwait</option>
        <option value='Kyrgyzstan'>Kyrgyzstan</option>
        <option value="Lao People's Democratic Republic">Laos</option>
        <option value='Lebanon'>Lebanon</option>
        <option value='Macao'>Macao</option>
        <option value='Malaysia'>Malaysia</option>
        <option value='Maldives'>Maldives</option>
        <option value='Mongolia'>Mongolia</option>
        <option value='Myanmar'>Myanmar (Burma)</option>
        <option value='Nepal'>Nepal</option>
        <option value='Oman'>Oman</option>
        <option value='Pakistan'>Pakistan</option>
        <option value='Palestinian Territory, Occupied'>Palestine</option>
        <option value='Philippines'>Philippines</option>
        <option value='Qatar'>Qatar</option>
        <option value='Russian Federation'>Russia</option>
        <option value='Saudi Arabia'>Saudi Arabia</option>
        <option value='Singapore'>Singapore</option>
        <option value='Sri Lanka'>Sri Lanka</option>
        <option value='Syrian Arab Republic'>Syria</option>
        <option value='Taiwan, Province of China'>Taiwan</option>
        <option value='Tajikistan'>Tajikistan</option>
        <option value='Thailand'>Thailand</option>
        <option value='Timor-Leste'>Timor-Leste</option>
        <option value='Turkey'>Turkey</option>
        <option value='Turkmenistan'>Turkmenistan</option>
        <option value='United Arab Emirates'>United Arab Emirates</option>
        <option value='Uzbekistan'>Uzbekistan</option>
        <option value='Viet Nam'>Vietnam</option>
        <option value='Yemen'>Yemen</option>
      </optgroup>
    </>
  )
}
